[General]
bypass-system = true
private-ip-answer = true
always-ip-address = true
dns-server = quic://918b1bdd.d.adguard-dns.com
update-url = https://sergibon.github.io/shadowrocket/base.conf
skip-proxy = 192.168.1.0/24, 192.168.0.0/16, localhost
tun-excluded-routes = 127.0.0.0/8, 192.0.0.0/24, 192.168.0.0/16, 255.255.255.255/32

[Rule]
RULE-SET,https://sergibon.github.io/shadowrocket/reject.list,REJECT
RULE-SET,https://sergibon.github.io/shadowrocket/whitelist/white-global.list,DIRECT
FINAL,PROXY