[General]
bypass-system = true
private-ip-answer = true
always-ip-address = true
dns-server = quic://918b1bdd.d.adguard-dns.com
fallback-dns-server = 94.140.14.14,94.140.15.15
dns-server = quic://918b1bdd.d.adguard-dns.com
update-url = https://sergibon.github.io/shadowrocket/base.conf
skip-proxy = 127.0.0.0/8, 192.0.0.0/24, 192.168.0.0/16, 255.255.255.255/32, localhost
tun-excluded-routes = 127.0.0.0/8, 192.0.0.0/24, 192.168.0.0/16, 255.255.255.255/32, localhost

[Rule]
RULE-SET,https://sergibon.github.io/shadowrocket/reject.list,REJECT
RULE-SET,https://sergibon.github.io/shadowrocket/whitelist/white-global.list,DIRECT

IP-CIDR,31.131.253.250/32,VPN
DOMAIN-SUFFIX,4pda.to,VPN
DOMAIN-SUFFIX,push.apple.com,VPN

DOMAIN-SUFFIX,.рф,RUSLIST
DOMAIN-SUFFIX,.ru,RUSLIST
GEOIP,RU,RUSLIST
FINAL,PROXY