[General]
include=base.conf
dns-server = system
update-url=https://sergibon.github.io/shadowrocket/cellular.conf

[Rule]
# DIRECT
RULE-SET,https://sergibon.github.io/shadowrocket/whitelist/white.list,DIRECT
