[General]
bypass-system = true
private-ip-answer = true
always-ip-address = true
tun-excluded-routes = 192.168.1.0/24
dns-server = quic://918b1bdd.d.adguard-dns.com
update-url = https://sergibon.github.io/shadowrocket/default.conf

[Rule]
DOMAIN-SUFFIX,youtube.com,🇷🇺RUS
DOMAIN-SUFFIX,youtubei.googleapis.com,🇷🇺RUS
DOMAIN-KEYWORD,ytimg.com,🇷🇺RUS
# DIRECT
RULE-SET,https://sergibon.github.io/shadowrocket/whitelist/white-global.list,DIRECT
# RU
GEOIP,RU,🇷🇺
# PROXY
FINAL,PROXY

[Host]
localhost = 127.0.0.1
