[General]
include = base.conf
skip-proxy = 45.147.200.187
update-url = https://sergibon.github.io/shadowrocket/default.conf

[Rule]
DOMAIN-SUFFIX,youtube.com,🇷🇺RUS
DOMAIN-SUFFIX,googlevideo.com,🇷🇺RUS
GEOIP,RU,🇷🇺RUS