[General]
skip-proxy = 45.147.200.187
include = base.conf
update-url = https://sergibon.github.io/shadowrocket/default.conf

[Rule]
# FIN
DOMAIN-SUFFIX,4pda.to,🇫🇮FIN
DOMAIN-SUFFIX,habr.com,🇫🇮FIN
DOMAIN-SUFFIX,openai.com,🇫🇮FIN
DOMAIN-SUFFIX,chatgpt.com,🇫🇮FIN
DOMAIN-SUFFIX,reddit.com,🇫🇮FIN
DOMAIN-SUFFIX,redditstatic.com,🇫🇮FIN