[General]
include = base.conf
fallback-dns-server = system
update-url = https://sergibon.github.io/shadowrocket/mobile.conf

[Proxy Group]
BYPASS = select,policy-regex-filter=^(?=.*🇷🇺)(?=.*LTE).*

[Rule]
RULE-SET,   https://sergibon.github.io/shadowrocket/whitelist/white.list,   DIRECT
FINAL,      BYPASS