[General]
include=base.conf
update-url=https://sergibon.github.io/shadowrocket/mobile.conf

[Rule]
# DIRECT
RULE-SET,https://sergibon.github.io/shadowrocket/white.list,DIRECT

[Host]
localhost=127.0.0.1
