[General]
include=base.conf
update-url = https://sergibon.github.io/shadowrocket/wlan.conf

[Rule]
# FIN
DOMAIN-SUFFIX,4pda.to,🇫🇮FIN
DOMAIN-SUFFIX,habr.com,🇫🇮FIN
DOMAIN-SUFFIX,openai.com,🇫🇮FIN
DOMAIN-SUFFIX,chatgpt.com,🇫🇮FIN
DOMAIN-SUFFIX,reddit.com,🇫🇮FIN
DOMAIN-SUFFIX,redditstatic.com,🇫🇮FIN
# RU
# GEOIP,RU,🇷🇺RUS
